version: '3'

services:

  playwing:
    container_name: playwing
    build:
      context: ./docker
    working_dir: /var/www/symfony
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/symfony
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/env.docker:/var/www/ua.apm.api-local/.env
      - ./docker/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      playwing-common:

networks:
  playwing-common:
